
### 取得列表
GET http://localhost:8080/categorys HTTP/1.1
Content-Type: application/json

### 取得單一
GET http://localhost:8080/categorys/12 HTTP/1.1
Content-Type: application/json

### 新增
POST http://localhost:8080/categorys HTTP/1.1
Content-Type: application/json

{
  "name": "Fruit"
}

### 更新
PATCH http://localhost:8080/categorys/1 HTTP/1.1
Content-Type: application/json

{
  "email": "summer@gmail.com",
  "name": "Summer Chen",
  "password": "aa1234"
}

### 刪除
DELETE http://localhost:8080/categorys/12 HTTP/1.1
Content-Type: application/json
