version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "80:8080"
    restart: unless-stopped
    # command: sh -c "yarn migrate deploy"
