version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: postgres
    ports:
      - "55001:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

# volumes:
#   postgres-data:







# docker run --name basic-postgres --rm -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=4y7sV96vA9wv46VR -e PGDATA=/var/lib/postgresql/data/pgdata -v /tmp:/var/lib/postgresql/data -p 5432:5432 -it postgres:14.1-alpine
